
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary':                    '#ffb4a8',
        'on-primary':                 '#690000',
        'primary-container':          '#8b0000',
        'on-primary-container':       '#ff907f',
        'primary-fixed':              '#ffdad4',
        'primary-fixed-dim':          '#ffb4a8',
        'on-primary-fixed':           '#410000',
        'on-primary-fixed-variant':   '#920703',
        'secondary':                  '#ffb4aa',
        'on-secondary':               '#5f1410',
        'secondary-container':        '#812d26',
        'on-secondary-container':     '#ff9f93',
        'secondary-fixed':            '#ffdad5',
        'secondary-fixed-dim':        '#ffb4aa',
        'on-secondary-fixed':         '#410001',
        'on-secondary-fixed-variant': '#7e2b23',
        'tertiary':                   '#bcc3ff',
        'on-tertiary':                '#001a98',
        'tertiary-container':         '#0025c8',
        'on-tertiary-container':      '#9ea9ff',
        'tertiary-fixed':             '#dfe0ff',
        'tertiary-fixed-dim':         '#bcc3ff',
        'on-tertiary-fixed':          '#000d60',
        'on-tertiary-fixed-variant':  '#0d2ccc',
        'error':                      '#ffb4ab',
        'on-error':                   '#690005',
        'error-container':            '#93000a',
        'on-error-container':         '#ffdad6',
        'surface':                    '#240c0c',
        'surface-dim':                '#240c0c',
        'surface-bright':             '#4f3130',
        'surface-container-lowest':   '#1d0807',
        'surface-container-low':      '#2d1413',
        'surface-container':          '#321817',
        'surface-container-high':     '#3e2221',
        'surface-container-highest':  '#4a2d2b',
        'surface-variant':            '#4a2d2b',
        'surface-tint':               '#ffb4a8',
        'on-surface':                 '#ffdad7',
        'on-surface-variant':         '#e3beb8',
        'on-background':              '#ffdad7',
        'background':                 '#240c0c',
        'outline':                    '#aa8984',
        'outline-variant':            '#5a403c',
        'inverse-surface':            '#ffdad7',
        'inverse-on-surface':         '#452927',
        'inverse-primary':            '#b52619',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.125rem',
        md: '0.25rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body:     ['Inter', 'sans-serif'],
        label:    ['Inter', 'sans-serif'],
      },
      animation: {
        'gradient-pulse': 'pulse-gradient 8s ease-in-out infinite',
        'fade-up':        'fade-up 0.6s ease-out forwards',
        'fade-in':        'fade-in 0.8s ease-out forwards',
      },
      keyframes: {
        'pulse-gradient': {
          '0%, 100%': { opacity: '0.15' },
          '50%':      { opacity: '0.3'  },
        },
        'fade-up': {
          '0%':   { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)'    },
        },
        'fade-in': {
          '0%':   { opacity: '0' },
          '100%': { opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}